version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u "bharathnoddy" -p "Btbh@j85"
      - docker build  -t bharathnoddy/sample-nginx:latest .
      - docker push bharathnoddy/sample-nginx:latest
