version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docekr login -u "bharathnoddy" -p "Btbh@j85"
      - export GIT_SHA="`git rev-parse HEAD`"
      - export GIT_COMMIT_MESSAGE="`git --no-pager log -1 --pretty=format:%s`"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t bharathnoddy/sample-nginx:1 .

 post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push bharathnoddy/sample-nginx:$GIT_SHA
